[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python web_app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
GOOGLE_MAPS_API_KEY = { default = "" }
PORT = { default = "5000" }
